"""
Django settings for neurofit project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os, sys
import raven
#from django.conf.global_settings import DEFAULT_FROM_EMAIL

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$k$a4#8-acjwnktv4una0+i&d6yjmml-#m887(md$l++kan09u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True
# Redirect all HTTP to HTTPS (shouldn't be needed, Apache handles it)
SECURE_SSL_REDIRECT = True
X_FRAME_OPTIONS = 'ALLOWALL' # default SAMEORIGIN


# DB id of current Site
#SITE_ID = 1


# Application definition

INSTALLED_APPS = (
	'ckeditor',
	'ckeditor_uploader',
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
#	'django.contrib.sites',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'people',
	'cnmb',
	'raven.contrib.django.raven_compat',
)

MIDDLEWARE_CLASSES = (
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'neurofit.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [os.path.join(BASE_DIR, 'templates')],
#		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
			'loaders': [
				('django.template.loaders.cached.Loader', [
					'django.template.loaders.filesystem.Loader',
					'django.template.loaders.app_directories.Loader',
				]),
			],
		},
	},
]

WSGI_APPLICATION = 'neurofit.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.mysql',
		'NAME': 'neurofit_django',
		'USER': 'root',
		'PASSWORD': 'password',
	}
}

# Seconds to keep each DB connection open between requests
# (default is 0, None means forever)
CONN_MAX_AGE = 30


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
	os.path.join(BASE_DIR, 'static'),
)

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ^^^ ADDED /neurofit TO URL BECAUSE THAT'S APACHE BASE URL FOR DJANGO


# Auth-related urls

# Default redirect after login
LOGIN_REDIRECT_URL = '/cnmb/'

LOGIN_URL = '/auth/login/'
LOGOUT_URL = '/auth/logout/'


# Email settings
DEFAULT_FROM_EMAIL = 'postmaster@support.neuro-fit.com'
ADMINS = (
	('Admin', 'postmaster@support.neuro-fit.com'),
)
EMAIL_SUBJECT_PREFIX = '[Neuro-fit site] '
EMAIL_HOST = 'smtp.mailgun.org'
EMAIL_DOMAIN = "support.neuro-fit.com"
EMAIL_API = "key-c2bb00ea011ddd59c076ea458bc413e2"
EMAIL_SUPPORT = "postmaster@support.neuro-fit.com"
EMAIL_PORT = "587"


# Logging
LOGGING = {
	'version': 1,
	'disable_existing_loggers': False,
	'handlers': {
		'console': {
			'class': 'logging.StreamHandler',
			'stream': sys.stderr,
		},
		'file': {
			'class': 'logging.FileHandler',
			'filename': os.path.join(BASE_DIR, 'LOG'),
		},
	},
	'loggers': {
		'cnmb': {
			'handlers': ['file'],
			'level': 'DEBUG',
		},
	},
}


# django-ckeditor

CKEDITOR_JQUERY_URL = None

CKEDITOR_UPLOAD_PATH = 'uploads/'

CKEDITOR_CONFIGS = {
'default': {
	'extraPlugins': 'filetools,uploadimage,oembed',
	'filebrowserBrowseUrl': '/ckeditor/browse/', # reverse('ckeditor_browse')
	'filebrowserUploadUrl': '/ckeditor/upload/', # reverse('ckeditor_upload')
	'toolbar': 'Custom1',
	'toolbar_Custom1': [
		['Cut', 'Copy', 'Paste'],
		['NumberedList', 'BulletedList', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight'],
		['Link', 'Unlink'],
		['Table', 'Image', 'oembed'],
		['Source'],
		'/', # row break
		['Bold', 'Italic', 'Underline', 'Strike'],
		['Styles', 'Format', 'Font', 'FontSize'],
		['TextColor', 'BGColor'],
	],
}
}

# raven


RAVEN_CONFIG = {
    'dsn': 'https://95660c57fb734889a4fb067b497b1cd5:4ad67bed02184c43b84ea2cb69098f9e@sentry.io/291707',
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    'release': raven.fetch_git_sha(os.path.abspath(os.curdir)),
}

try:
	from .settings_local import *
except:
	pass
